spin_manifest_version = 2

[application]
name = "spin-production-hours"
version = "0.1.0"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "A small web api for calculating production hours"

[[trigger.http]]
route = "/..."
component = "spin-production-hours"

[component.spin-production-hours]
source = "main.wasm"
allowed_outbound_hosts = []
[component.spin-production-hours.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
